import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/provider/ThemeProvider"
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import { Separator } from "@/components/ui/separator";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <ThemeProvider attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange  >
          <Navbar />
          {children}
          <Separator />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
